spring.application.name=storyloom-auth-service

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/storyloom-auth-db
spring.datasource.username=postgres
spring.datasource.password=6005073256

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=UTC


#Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=codeorg51@gmail.com
spring.mail.password=kdluifzvwflcgdsg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.email.from=codeorg51@gmail.com

# OTP Configuration
otp.expiration.minutes=5

#JWT Configuration

jwt.secret=Kag6Swn1LY70OkV3qYM00sDVQaqopGlroMsKoJpDAr6
#15 mins
jwt.expiration=900000 
#7 days
jwt.refresh.expiration=604800000 



